In [2]:
import numpy as np
import statistics
from statistics import mean, pvariance
import scipy
from scipy.optimize import minimize,NonlinearConstraint

# Python Lambda Functions
notes and and examples

In [3]:
#7 is inputted as argument
#funtion evaluates to x, which is 12 in this case

x = lambda a: a + 5
print(x(7))

12


In [4]:
#lambda function with multiple arguments

x = lambda a,b,c: a*b + c
print(x(3,6,10))

28


In [5]:
#nested lambda function that doubles a number

def function(n):
    return lambda a: a*n

double_number = function(2)
print(double_number(13))

26


# Minimizing Basic Functions

In [6]:
#defines the function to be minimized
def fun(x):
    return x**2 - x + 3
    
x0 = np.array([4])

res = minimize(fun,x0)
print(res.x, res.fun) #prints array of solutions and f(x) value at x

[0.5] 2.75


# Implementing Variance

In [ ]:
#defines the covariance matrix x, weights, and vector of ones a
r = np.array([[504,360,180],[360,360,0],[180,0,720]])
w0 = np.array([.35,.45,.2])
a = np.ones(len(w))

#defines a lambda function that returns dot product of weights and array of ones
fun = lambda w: np.dot(w,a)

print("The sum of all the weights is:")
print(fun(w))

#nonlinear constraint that implements the function and sets the constraint bounds
con = NonlinearConstraint(fun(w),1,1)

#defines a lambda function that implements the variance equation (int_var truncates value from var)
var = lambda w,r: np.dot(np.dot(w,r),w)

print("The variance is:")
print(var(w,r))

int_var = var(w,r)

#minimization method ()
res.x = minimize(int_var,w,method='Nelder-Mead',constraints=con)
print(res.x)

# Simple Implementation of Variance

In [9]:
#defines the covariance matrix r, weights, and vector of ones a
r = np.array([[504,360,180],[360,360,0],[180,0,720]])
w0 = np.array([.35,.45,.2])
a = np.ones(len(w0))

#defines a lambda function that returns dot product of weights and array of ones
func = lambda w: np.dot(w,a)

print("The sum of all the weights is:")
print(fun(np.array([.2,.5,.3])))

print()

#nonlinear constraint that implements the function and sets the constraint bounds
const = NonlinearConstraint(func(np.array([.2,.5,.3])),1,1)

#defines a lambda function that implements the variance equation
lvar = lambda w: (sum((w - mean(w))**2)) / len(w)

print("The variance by lambda function is:")
print(lvar(np.array([.2,.5,.3])))

print("The variance checked by statistics package is:")
print(pvariance(np.array([.2,.5,.3]))) #checks variance using pvariance method from statistics

print()

#minimization method
minimize_method = minimize(lvar,w0,method='Nelder-Mead',bounds=(1,1)) #,constraints=const)

print("The solution array for the weights is:")
print(minimize_method.x)

The sum of all the weights is:
[2.84 2.75 2.79]

The variance by lambda function is:
0.015555555555555557
The variance checked by statistics package is:
0.015555555555555555

The solution array for the weights is:
[0.28509724 0.28509482 0.28509537]


In [17]:
#basic implementation of the minimization method
ex_weights = np.array([12])

bound_func = lambda x: x**3 + 3
ex_con = NonlinearConstraint(bound_func,-1,1)

func = lambda x: 3*x**2

ex_minimize_method = minimize(func,ex_weights, method='Nelder-Mead',constraints=ex_con)

print(ex_minimize_method)

 final_simplex: (array([[-2.84217094e-14],
       [ 7.32421875e-05]]), array([2.42338070e-27, 1.60932541e-08]))
           fun: 2.4233807008389483e-27
       message: 'Optimization terminated successfully.'
          nfev: 42
           nit: 21
        status: 0
       success: True
             x: array([-2.84217094e-14])


# Code to Confirm Final Solution for Weights

In [6]:
#check
def sol(a,r):
    r_inv = np.linalg.inv(r)
    cov_mat = np.dot(r_inv,a) #matrix inverse
    nested_inv = (np.dot(a,cov_mat)) #matrix inverse
    
    solution = cov_mat / nested_inv
    return solution

print(sol(a,r)) #should be array but why

[-0.52631579  1.10526316  0.42105263]
